### ISSUE TITLE
Ansys version naming: 2020R1 -> AWP_ROOT201, 2020R2 -> AWP_ROOT202?

### ISSUE THREAD

**Issue by xiepei1** [pyansys/DPF-Core#31]
Hi guys,

Just pip installed the dpf-core, when i run examples (conda create new env. with Python 3.7, running OS: Windows 10, both Ansys 2020R1 & R2 installed), always found "InvalidANSYSVersionError: Ansys v202 does not support DPF", but acc. to Help document, it should somehow work for Ansys 2020R1 and above...

Looking at the source code, found that seemingly multiple places refer 2020R1 as AWP_ROOT211, 2020R2 as AWP_ROOT212.

did i get it right that the naming to be so? i found my installation in my workstation, 2020R1 as v201, 2020R2 as v202.

Not completely sure that i get the reason correct...

Thank you guys,

Regards, 

Xie Pei

**Comment by jazztekk** [comment]
Hi, Xie -

The environment variable name encoding has the form AWP_ROOTYYR (YY corresponds to the last two digits of the year, R is the release number).  For example:

AWP_ROOT201 => ANSYS 2020 R1
AWP_ROOT202 => ANSYS 2020 R2
AWP_ROOT211 => ANSYS 2021 R1

You'll want to try versions ANSYS 2021 R1 or later.

Could you please point us to the incorrect Doc reference?

Thank you, Xie

jazztekk

**Comment by akaszynski** [comment]
Thanks for answering this @jazztekk, was about to respond.

In regards to support for 2020R1, it's not something that we have planned to support since DPF was in early internal development and 2020R2 is the officially supported version.

We'll be sure to correct the docs to remove the confusion.

**Comment by xiepei1** [comment]
> Hi, Xie -
> 
> The environment variable name encoding has the form AWP_ROOTYYR (YY corresponds to the last two digits of the year, R is the release number). For example:
> 
> AWP_ROOT201 => ANSYS 2020 R1
> AWP_ROOT202 => ANSYS 2020 R2
> AWP_ROOT211 => ANSYS 2021 R1
> 
> You'll want to try versions ANSYS 2021 R1 or later.
> 
> Could you please point us to the incorrect Doc reference?
> 
> Thank you, Xie
> 
> jazztekk

Thank you very much for pointing out that the support starting from 2021R1.... was my bad not noticing 1 or 0 :-(

**Comment by xiepei1** [comment]
> Thanks for answering this @jazztekk, was about to respond.
> 
> In regards to support for 2020R1, it's not something that we have planned to support since DPF was in early internal development and 2020R2 is the officially supported version.
> 
> We'll be sure to correct the docs to remove the confusion.

knowing 2020R2 is also DPF officially supported version was great, but not planned was sad... one point is that in many real life use cases, not all the guys tend to use the latest version of Ansys, which is one of the difficulties sometimes i could encounter in some projects....

**Comment by akaszynski** [comment]
We can package a standalone version of DPF for windows (there's already a docker image for linux and windows) if you'd like.
