### ISSUE TITLE
Operator("cplx_multiply")

### ISSUE THREAD

**Issue by xiepei1** [pyansys/DPF-Core#33]
```
import ansys.dpf.core as dpf
import numpy as np
from ansys.dpf.core import examples

rst = dpf.DataSources(examples.static_rst)

s1_op = dpf.Operator("S1")
s1_op.inputs.data_sources.connect(rst)

s2_op = dpf.Operator("S2")
s2_op.inputs.data_sources.connect(rst)

# multiply 'S1' and 'S2'
mp_op = dpf.Operator("cplx_multiply")
mp_op.inputs.fields_containerA.connect(s1_op.outputs.fields_container)
mp_op.inputs.fields_containerB.connect(s2_op.outputs.fields_container)
# however, here it does not work, there is no field in the result
print(mp_op.outputs.fields_container())

# the intended result, but this takes long time to compute for large models
res = np.multiply(s1_op.outputs.fields_container()[0].data,
                  s2_op.outputs.fields_container()[0].data)
```
how is the Operator multiply working? it should work with 2 fields container, but it does not work out, getting results back...

to confirm that i am using it the right way, or not...

**Comment by akaszynski** [comment]
Looking into this and I'll get back to you.

**Comment by akaszynski** [comment]
Thanks for posting the minimum working example!

I'm not a DPF expert, but as far as I can tell, the reason why `'cplx_multiply'` isn't working is because the fields_container fields aren't complex.  The operator you're really looking for is the `'dot'` operator, which actually uses the `*` Python operator.  For example:

```py
import ansys.dpf.core as dpf
import numpy as np
from ansys.dpf.core import examples

dpf.connect_to_server()
rst = dpf.DataSources(examples.static_rst)

s1_op = dpf.Operator("S1")
s1_op.inputs.data_sources.connect(rst)

s2_op = dpf.Operator("S2")
s2_op.inputs.data_sources.connect(rst)

# compute with numpy
res = np.multiply(s1_op.outputs.fields_container()[0].data,
                  s2_op.outputs.fields_container()[0].data)

# compute with dpf
dpf_res = (s1_op * s2_op).outputs.field().data

# should be identical
assert np.allclose(dpf_res, res)
```

Really, the `s1_op * s2_op` just uses the `Dot` operator under the hood:
https://github.com/pyansys/DPF-Core/blob/cdefeb4d8bb537d4a41eb9e0fecf0698170e2de9/ansys/dpf/core/dpf_operator.py#L298-L307

Please let me know if you need any additional help.

@rlagha, would be great if we had an example for multiplication.

**Comment by xiepei1** [comment]
> Thanks for posting the minimum working example!
> 
> I'm not a DPF expert, but as far as I can tell, the reason why `'cplx_multiply'` isn't working is because the fields_container fields aren't complex. The operator you're really looking for is the `'dot'` operator, which actually uses the `*` Python operator. For example:
> 
> ```python
> import ansys.dpf.core as dpf
> import numpy as np
> from ansys.dpf.core import examples
> 
> dpf.connect_to_server()
> rst = dpf.DataSources(examples.static_rst)
> 
> s1_op = dpf.Operator("S1")
> s1_op.inputs.data_sources.connect(rst)
> 
> s2_op = dpf.Operator("S2")
> s2_op.inputs.data_sources.connect(rst)
> 
> # compute with numpy
> res = np.multiply(s1_op.outputs.fields_container()[0].data,
>                   s2_op.outputs.fields_container()[0].data)
> 
> # compute with dpf
> dpf_res = (s1_op * s2_op).outputs.field().data
> 
> # should be identical
> assert np.allclose(dpf_res, res)
> ```
> 
> Really, the `s1_op * s2_op` just uses the `Dot` operator under the hood:
> https://github.com/pyansys/DPF-Core/blob/cdefeb4d8bb537d4a41eb9e0fecf0698170e2de9/ansys/dpf/core/dpf_operator.py#L298-L307
> 
> Please let me know if you need any additional help.
> 
> @rlagha, would be great if we had an example for multiplication.

Thank you very much Alex! works fine now...

I would also think that if there an example which demonstrates the capability of both pymapdl & dpf-core. I see great performance of dpf-core in terms of chaining operators, yet still we have many cases which require rather complex post-process procedures (which means we have rather long APDL scripts to operate in Ansys Classic or insert in Ansys Mechanical to *vwrite result files), in these cases, we need to pass, e.g. op.outputs.fields_container()[0].data to operate (example, find certain % of elements based on certain criteria), in this case, the solution i see is to use pymapdl to run, e.g., a lot of mapdl.run() lines which is normally very fast in MAPDL solver...

**Comment by akaszynski** [comment]
> ., a lot of mapdl.run() lines which is normally very fast in MAPDL solver...

Are you seeing a performance bottleneck in `pymapdl`?  If so, post partial code there and we can help you out.  There are a few ways to make it much quicker (like `with mapdl.non_interactive:`).

**Comment by xiepei1** [comment]
> > ., a lot of mapdl.run() lines which is normally very fast in MAPDL solver...
> 
> 
> 
> Are you seeing a performance bottleneck in `pymapdl`?  If so, post partial code there and we can help you out.  There are a few ways to make it much quicker (like `with mapdl.non_interactive:`).

Up to now, I don't see a bottleneck yet, also already using maps.non_interactive

**Comment by rlagha** [comment]
@akaszynski , @xiepei1 Thanks for your feedback, yes we will bring more examples soon.
Regards
