### ISSUE TITLE
progess bar for loading .rst file data

### ISSUE THREAD

**Issue by mcMunich** [pyansys/DPF-Core#34]
This would be a nice feature, if possible. 
I am testing ansys.dpf to see if large rst files can be accessed with post.load_solution. 
The files are on a server and enormous (up to but not limited to 100GB). 
This naturally takes a while. 
Is there any switch to get a update/progress of the load?

**Comment by akaszynski** [comment]
Spoke with some DPF developers and realized that there's really two long running tasks:
- The result calculation
- The streaming of the results to the client.

The result calculation actually has a progress indicator, but that's not something exposed at the moment.  The result streaming is something we can add, however, for certain return types.  Can you provide a sample workflow and point out the long running parts so I can see what I can add on the client side?

**Comment by cbellot000** [comment]
A progress bar for getting and setting large amount of data has been added in this [PR](https://github.com/pyansys/DPF-Core/pull/35). It has also been added when uploading and downloading files (new feature).

For the result calculation part, the progress bar has not been added yet, it needs to be added server side, we each is planned for next release
