### ISSUE TITLE
description/name of the element type?

### ISSUE THREAD

**Issue by akaszynski** [pyansys/DPF-Core#48]
How can I get a human-understandable description/name of the element type? I have not found a way to access the list [here](https://dpfdocs.pyansys.com/api/ansys.dpf.core.elements.html#ansys.dpf.core.elements.element_types). Hopefully I am just missing something obvious. Thanks

_Originally posted by @HunterAtApex in https://github.com/pyansys/pymapdl/discussions/550_

**Comment by pmaroneh** [comment]
Not sure that there is a comprehensive list anywhere. These element types are the ones shown in Mechanical (for example when checking the mesh quality). 
Below is a partial list I had done some time ago, explaining what those are and what are their APDL equivalent is:
![image](https://user-images.githubusercontent.com/76440649/127977098-9eddf894-b93b-47c8-808c-bab005cda573.png)

**Comment by akaszynski** [comment]
Thanks for posting @pmaroneh!  I'll check internally, but if this turns out to be the correspondence, I'll have it added to our documentation (I've always been a MAPDL and not workbench user).

**Comment by HunterAtApex** [comment]
Thank you for the info! I was actually looking for a way to interpret the result of calling element.type(); it seems to return an integer, and I thought maybe the element_types class would be able to reveal the name like Tet4 for a specific integer value. Is the element_types class available in python?

In the documentation examples it shows this:
>>> element.type
<element_types.Hex20: 1>

But in my interpreter I only see this:
>>> element.type
1

**Comment by rlagha** [comment]
and you are right @HunterAtApex, we will introduce an ElementDescriptor class which will be easier to understand, we have it in C++ client, and definitely need the same in python.

**Comment by akaszynski** [comment]
We're going to get another release out soon (probably next week) as there's another feature to be added.
